base_to_footprint_ekf:
  ros__parameters:
    frequency: 20.0  #original was 50.0
    publish_tf: true
    transform_timeout: 0.01
    transform_time_offset: 0.045
    two_d_mode: false
    # diagnostics_agg: true

    pose0: base_to_footprint_pose
    pose0_config: [true,  true,  true,   # Use position (x, y, z)
                  true,  true,  true,    # Use orientation (roll, pitch, yaw)
                  false, false, false,   # vx, vy, vz
                  false, false, false,   # vroll, vpitch, vyaw
                  false, false, false]   # ax, ay, az

    imu0: imu/data
    # imu0_config: [false, false, false,
    #               false, false, false,
    #               true, true, true,
    #               false, false, false,
    #               false, false, false]
    imu0_config: [false, false, false, #X, Y, Z
                  true, true, true,    #roll, pitch, yaw                # Use orientation (roll, pitch, yaw)
                  false, false, false, #vx, vy, vz
                  true, true, true,    # Use angular velocity (vroll, vpitch, vyaw)
                  false, false, false] # Use linear acceleration (ax, ay, az); prevoiusly it was all true
    odom_frame: base_footprint
    world_frame: base_footprint